//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML.Bank.CentralBankServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MT103", Namespace="http://schemas.datacontract.org/2004/07/XML.CentralBank.Model")]
    [System.SerializableAttribute()]
    public partial class MT103 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayerBankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientBankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SWIFTPayerBankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SWIFTRecipientBankField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ammount {
            get {
                return this.AmmountField;
            }
            set {
                if ((this.AmmountField.Equals(value) != true)) {
                    this.AmmountField = value;
                    this.RaisePropertyChanged("Ammount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayerAccount {
            get {
                return this.PayerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerAccountField, value) != true)) {
                    this.PayerAccountField = value;
                    this.RaisePropertyChanged("PayerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayerBankAccountNumber {
            get {
                return this.PayerBankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerBankAccountNumberField, value) != true)) {
                    this.PayerBankAccountNumberField = value;
                    this.RaisePropertyChanged("PayerBankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientAccount {
            get {
                return this.RecipientAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientAccountField, value) != true)) {
                    this.RecipientAccountField = value;
                    this.RaisePropertyChanged("RecipientAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientBankAccountNumber {
            get {
                return this.RecipientBankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientBankAccountNumberField, value) != true)) {
                    this.RecipientBankAccountNumberField = value;
                    this.RaisePropertyChanged("RecipientBankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTPayerBank {
            get {
                return this.SWIFTPayerBankField;
            }
            set {
                if ((object.ReferenceEquals(this.SWIFTPayerBankField, value) != true)) {
                    this.SWIFTPayerBankField = value;
                    this.RaisePropertyChanged("SWIFTPayerBank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTRecipientBank {
            get {
                return this.SWIFTRecipientBankField;
            }
            set {
                if ((object.ReferenceEquals(this.SWIFTRecipientBankField, value) != true)) {
                    this.SWIFTRecipientBankField = value;
                    this.RaisePropertyChanged("SWIFTRecipientBank");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MT900", Namespace="http://schemas.datacontract.org/2004/07/XML.CentralBank.Model")]
    [System.SerializableAttribute()]
    public partial class MT900 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MTMessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayerBankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SWIFTPayerBankField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ammount {
            get {
                return this.AmmountField;
            }
            set {
                if ((this.AmmountField.Equals(value) != true)) {
                    this.AmmountField = value;
                    this.RaisePropertyChanged("Ammount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MTMessageId {
            get {
                return this.MTMessageIdField;
            }
            set {
                if ((this.MTMessageIdField.Equals(value) != true)) {
                    this.MTMessageIdField = value;
                    this.RaisePropertyChanged("MTMessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayerBankAccountNumber {
            get {
                return this.PayerBankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PayerBankAccountNumberField, value) != true)) {
                    this.PayerBankAccountNumberField = value;
                    this.RaisePropertyChanged("PayerBankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTPayerBank {
            get {
                return this.SWIFTPayerBankField;
            }
            set {
                if ((object.ReferenceEquals(this.SWIFTPayerBankField, value) != true)) {
                    this.SWIFTPayerBankField = value;
                    this.RaisePropertyChanged("SWIFTPayerBank");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MT910", Namespace="http://schemas.datacontract.org/2004/07/XML.CentralBank.Model")]
    [System.SerializableAttribute()]
    public partial class MT910 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MTMessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientBankAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SWIFTRecipientBankField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ammount {
            get {
                return this.AmmountField;
            }
            set {
                if ((this.AmmountField.Equals(value) != true)) {
                    this.AmmountField = value;
                    this.RaisePropertyChanged("Ammount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MTMessageId {
            get {
                return this.MTMessageIdField;
            }
            set {
                if ((this.MTMessageIdField.Equals(value) != true)) {
                    this.MTMessageIdField = value;
                    this.RaisePropertyChanged("MTMessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientBankAccountNumber {
            get {
                return this.RecipientBankAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientBankAccountNumberField, value) != true)) {
                    this.RecipientBankAccountNumberField = value;
                    this.RaisePropertyChanged("RecipientBankAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTRecipientBank {
            get {
                return this.SWIFTRecipientBankField;
            }
            set {
                if ((object.ReferenceEquals(this.SWIFTRecipientBankField, value) != true)) {
                    this.SWIFTRecipientBankField = value;
                    this.RaisePropertyChanged("SWIFTRecipientBank");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CentralBankServiceReference.ICentralBankService", CallbackContract=typeof(XML.Bank.CentralBankServiceReference.ICentralBankServiceCallback))]
    public interface ICentralBankService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICentralBankService/RTGSRequest")]
        void RTGSRequest(XML.Bank.CentralBankServiceReference.MT103 requestMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICentralBankService/RTGSRequest")]
        System.Threading.Tasks.Task RTGSRequestAsync(XML.Bank.CentralBankServiceReference.MT103 requestMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralBankService/RegisterBankClient", ReplyAction="http://tempuri.org/ICentralBankService/RegisterBankClientResponse")]
        bool RegisterBankClient(string bankId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralBankService/RegisterBankClient", ReplyAction="http://tempuri.org/ICentralBankService/RegisterBankClientResponse")]
        System.Threading.Tasks.Task<bool> RegisterBankClientAsync(string bankId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralBankServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICentralBankService/MT103Callback")]
        void MT103Callback(XML.Bank.CentralBankServiceReference.MT103 message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICentralBankService/MT900CallBack")]
        void MT900CallBack(XML.Bank.CentralBankServiceReference.MT900 message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICentralBankService/MT910CallBack")]
        void MT910CallBack(XML.Bank.CentralBankServiceReference.MT910 message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralBankServiceChannel : XML.Bank.CentralBankServiceReference.ICentralBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentralBankServiceClient : System.ServiceModel.DuplexClientBase<XML.Bank.CentralBankServiceReference.ICentralBankService>, XML.Bank.CentralBankServiceReference.ICentralBankService {
        
        public CentralBankServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CentralBankServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CentralBankServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CentralBankServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CentralBankServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RTGSRequest(XML.Bank.CentralBankServiceReference.MT103 requestMessage) {
            base.Channel.RTGSRequest(requestMessage);
        }
        
        public System.Threading.Tasks.Task RTGSRequestAsync(XML.Bank.CentralBankServiceReference.MT103 requestMessage) {
            return base.Channel.RTGSRequestAsync(requestMessage);
        }
        
        public bool RegisterBankClient(string bankId) {
            return base.Channel.RegisterBankClient(bankId);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterBankClientAsync(string bankId) {
            return base.Channel.RegisterBankClientAsync(bankId);
        }
    }
}
